Pa 327
hazelcast/client-compatibility-suites pull request #131
Opened 2024-09-11 14:23 UTC by sergvatu

2024-09-11 14:50 UTC, srknzl approved these changes

2024-09-12 11:17 UTC, ihsandemir requested changes
Please write description on what is your change about.

2024-09-12 14:34 UTC, sergvatu commented on .github/workflows/java_thin_client_compatibility.yaml
>        branch_name:
Sure, will do

2024-09-12 17:36 UTC, sergvatu commented on .github/workflows/server_compatibility.yaml
> +      - name: Build JARs Maven Version ${{ steps.set_up_hz_server_version.outputs.HAZELCAST_SERVER_VERSION }}
I've made this change

2024-09-13 07:35 UTC, ihsandemir approved these changes

2024-09-13 10:32 UTC, merged